More mingw

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,24 +10,36 @@ inputs:
     required: true
   target-arch:
     description: "Architecture - x86 or x64. Only used on Windows"
-    required: false
-    default: 'x64'
+    required: true
   toolchain:
-    description: "Toolchain - mingw64 or vc. Only used on Windows"
-    required: false
+    description: "Toolchain - msys2 or vc. Only used on Windows"
+    required: true
 
 runs:
   using: 'composite'
   steps:
 
-    # Validation
+    # Validation of inputs
 
-    - name: Validate Visual C++ inputs
-      if: runner.os == 'windows' && (inputs.toolchain == '' || ! contains('vc,mingw64', inputs.toolchain))
+    - name: Validate toolchain on Windows
+      if: runner.os == 'windows' && (inputs.toolchain == '' || ! contains('vc,msys2', inputs.toolchain))
       shell: pwsh
       run: |
-        echo "Toolchain is ${{ inputs.toolchain }}"
-        echo "::error::Invalid toolchain value (${{ inputs.toolchain }}.) Must be vc or mingw64."
+        echo "::error::Invalid toolchain value (${{ inputs.toolchain }}.) Must be vc or msys2."
+        exit 1
+
+    - name: Validate target-arch for Visual C++
+      if: runner.os == 'windows' && inputs.toolchain == 'vc' && ! contains('x86,x64', inputs.target-arch))
+      shell: pwsh
+      run: |
+        echo "::error::Invalid target-arch value (${{ inputs.target-arch }}.) Must be x86 or x64."
+        exit 1
+
+    - name: Validate target-arch for msys2
+      if: runner.os == 'windows' && inputs.toolchain == 'mingw' && ! contains('mingw32,mingw64', inputs.target-arch))
+      shell: pwsh
+      run: |
+        echo "::error::Invalid target-arch value (${{ inputs.target-arch }}.) Must be mingw32 or mingw64."
         exit 1
 
     # Set up environment variables that can be used by steps below as well
@@ -42,7 +54,7 @@ runs:
         echo "IMAGEOS=${ImageOS}" >> $env:GITHUB_ENV
         echo "TCLDIR=${{ runner.temp }}/tcl/${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
         echo "TCLSUBDIR=${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
-        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs" >> $env:GITHUB_ENV
+        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs/${{ inputs.target-arch }}" >> $env:GITHUB_ENV
 
     - name: Set Tcl path for non-Windows
       if: runner.os != 'Windows'
@@ -83,8 +95,8 @@ runs:
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }}
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} install
 
-    - name: Build Tcl on Windows with MingW64
-      if: runner.os == 'Windows' && inputs.toolchain == 'mingw64' && steps.tcl-cache.outputs.cache-hit != 'true'
+    - name: Build Tcl on Windows with msys2
+      if: runner.os == 'Windows' && inputs.toolchain == 'msys2' && steps.tcl-cache.outputs.cache-hit != 'true'
       working-directory: tcl-${{ inputs.tcl-tag }}/win
       shell: msys2 {0}
       run: |
