mingw fixes (#2)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,38 +10,81 @@ inputs:
     required: true
   target-arch:
     description: "Architecture - x86 or x64. Only used on Windows"
-    required: false
-    default: 'x64'
+    required: true
   toolchain:
-    description: "Toolchain - mingw64 or vc. Only used on Windows"
-    required: false
-    default: 'vc'
+    description: "Toolchain - msys2 or vc. Only used on Windows"
+    required: true
 
 runs:
   using: 'composite'
   steps:
-    - name: Set Tcl path for Windows
-      if: runner.os == 'Windows'
+
+    # Validation of inputs
+
+    - name: Validate toolchain on Windows
+      if: runner.os == 'windows' && (inputs.toolchain == '' || ! contains('vc,msys2', inputs.toolchain))
       shell: pwsh
       run: |
+        echo "::error::Invalid toolchain value (${{ inputs.toolchain }}.) Must be vc or msys2."
+        exit 1
+
+    - name: Validate target-arch for Visual C++
+      if: runner.os == 'windows' && inputs.toolchain == 'vc' && ! contains('x86,x64', inputs.target-arch)
+      shell: pwsh
+      run: |
+        echo "::error::Invalid target-arch value (${{ inputs.target-arch }}.) Must be x86 or x64."
+        exit 1
+
+    - name: Validate target-arch for msys2
+      if: runner.os == 'windows' && inputs.toolchain == 'mingw' && ! contains('mingw32,mingw64', inputs.target-arch)
+      shell: pwsh
+      run: |
+        echo "::error::Invalid target-arch value (${{ inputs.target-arch }}.) Must be mingw32 or mingw64."
+        exit 1
+
+    # Set up environment variables that can be used by steps below as well
+    # as steps in the caller workflow.
+    # NOTE: the preset IMAGEOS is explicitly set to itself else it is not available
+    # in the tcl-cache step below. No idea why.
+
+    - name: Set Tcl path for VC on Windows
+      if: runner.os == 'Windows' && inputs.toolchain == 'vc'
+      shell: pwsh
+      run: |
+        echo "IMAGEOS=${ImageOS}" >> $env:GITHUB_ENV
         echo "TCLDIR=${{ runner.temp }}/tcl/${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
         echo "TCLSUBDIR=${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}" >> $env:GITHUB_ENV
-        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs" >> $env:GITHUB_ENV
+        echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs/${{ inputs.target-arch }}" >> $env:GITHUB_ENV
+
+    - name: Set Tcl path for VC on Windows
+      if: runner.os == 'Windows' && inputs.toolchain == 'msys2'
+      shell: bash
+      run: |
+        echo IMAGEOS=`cygpath -m "${ImageOS}"` >> $GITHUB_ENV
+        echo TCLDIR=`cygpath -m "${{ runner.temp }}/tcl/${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}"` >> $GITHUB_ENV
+        echo TCLSUBDIR=`cygpath -m "${{ inputs.toolchain }}-${{ inputs.target-arch }}-${{ inputs.tcl-tag }}"` >> $GITHUB_ENV
+        echo TCLEXTRASDIR=`cygpath -m "${{ runner.temp }}/tcl-external-libs/${{ inputs.target-arch }}"` >> $GITHUB_ENV
 
     - name: Set Tcl path for non-Windows
       if: runner.os != 'Windows'
       shell: bash
       run: |
+        echo "IMAGEOS=${ImageOS}" >> $GITHUB_ENV
         echo "TCLDIR=${{ runner.temp }}/tcl/${{ inputs.tcl-tag }}" >> $GITHUB_ENV
         echo "TCLSUBDIR=${{ inputs.tcl-tag }}" >> $GITHUB_ENV
         echo "TCLEXTRASDIR=${{ runner.temp }}/tcl-external-libs" >> $GITHUB_ENV
+
+    # Cache Tcl so we do not have to rebuild everytime. Note runner.os
+    # does not suffice as subkey as it does not include os version. Hence
+    # we also include the OS image name (e.g. ubuntu20). And of course
+    # the Tcl tag.
 
     - name: Cache Tcl build
       id: tcl-cache
       uses: actions/cache@v4
       with:
         path: ${{ env.TCLDIR }}
-        key: ${{ runner.os }}-${{ env.ImageOS }}-tcl-${{ env.TCLSUBDIR }}
+        key: ${{ runner.os }}-${{ env.IMAGEOS }}-tcl-${{ env.TCLSUBDIR }}
 
     - name: Checkout Tcl
       if: steps.tcl-cache.outputs.cache-hit != 'true'
@@ -51,6 +94,8 @@ runs:
         ref: ${{ inputs.tcl-tag }}
         path: tcl-${{ inputs.tcl-tag }}
 
+    # Build Tcl as per the input configuration.
+
     - name: Build Tcl on Windows with nmake
       if: runner.os == 'Windows' && inputs.toolchain == 'vc' && steps.tcl-cache.outputs.cache-hit != 'true'
       working-directory: tcl-${{ inputs.tcl-tag }}/win
@@ -59,8 +104,8 @@ runs:
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }}
         nmake /s /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} install
 
-    - name: Build Tcl on Windows with MingW64
-      if: runner.os == 'Windows' && inputs.toolchain == 'mingw64' && steps.tcl-cache.outputs.cache-hit != 'true'
+    - name: Build Tcl on Windows with msys2
+      if: runner.os == 'Windows' && inputs.toolchain == 'msys2' && steps.tcl-cache.outputs.cache-hit != 'true'
       working-directory: tcl-${{ inputs.tcl-tag }}/win
       shell: msys2 {0}
       run: |
